### ISSUE TITLE
choose chapter then quit!

### ISSUE THREAD

**Issue by LeeHOSe** [Djaenk/zyBooks-Activity-Completer#1]
The code run but stop after creating a headless website.
The website was created but how can I choose what chapter or section to finish?

**Comment by nagyb1996** [comment]
[complete.zip](https://github.com/Djaenk/zyBooks-Activity-Completer/files/3531586/complete.zip)

try this

I updated the tag ID's

**Comment by LeeHOSe** [comment]
it return selenium.common.exception.NoSuchElementException, it quite fast I cant read the least of them.
The website do open but the code return error and close.

**Comment by Djaenk** [comment]
The id's of login elements were changed since the last commit. I've pushed a change which should fix this problem with the login. Further id changes should still be covered.

This change isn't reflected in the releases, though.
