### ISSUE TITLE
zybook xpath changes

### ISSUE THREAD

**Issue by JartanFTW** [Djaenk/zyBooks-Activity-Completer#12]
Looks like ZyBook has removed some of the whitespace in a bunch of their xpaths.
Along with this they did change some of the xpaths entirely too.
I'll make a branch and open a pull request to repair this.

**Comment by Djaenk** [comment]
Thank you, I'd appreciate the fixes. If you're able to and don't mind, could you replace broken xpaths with css selectors?

**Comment by JartanFTW** [comment]
Sure, I'll figure it out.
I'll also make a branch to add a feature that checks if the activity is completed already, and skips it if it is. I already did this on an old version I was tinkering with but didn't think to actually contribute it.

**Comment by JartanFTW** [comment]
Please invite me as a contributor so I can open a new branch.

**Comment by RoniJames** [comment]
@JartanFTW Would you mind sharing the new xpaths with me? I tried adding you on discord but it seems you have it set to block friend requests.

**Comment by JartanFTW** [comment]
> @JartanFTW Would you mind sharing the new xpaths with me? I tried adding you on discord but it seems you have it set to block friend requests.

I don't have it set to block friend requests. You might have your settings set to only allow friend requests from people in servers with you, or something similar.
I'll likely create a fork of this repository and make a pull request from that. I'll do so within the next few days.

**Comment by JartanFTW** [comment]
Decided against making a fork because I don't know how they work. I'll open a branch and commit the css selectors fix once I'm invited as a contributor.

**Comment by wcooperscott** [comment]
Any updates with this?

**Comment by JartanFTW** [comment]
> Any updates with this?

It's done. It's been done since the day after I opened this Issue. I just need to be invited as a contributor so I can open a branch and merge it into master/main.

**Comment by wcooperscott** [comment]
> > Any updates with this?
> 
> It's done. It's been done since the day after I opened this Issue. I just need to be invited as a contributor so I can open a branch and merge it into master/main.


That's great! @Djaenk @Boostem, could y'all?

Until then, is there a public repository of your changes I could use? This Java CS101 is on Zybooks...they won't let me take the final until I answer their 1000 questions.

**Comment by Boostem** [comment]
Why was I mentioned? You merged my PR from last year fixing headless mode :-)

**Comment by wcooperscott** [comment]
> Why was I mentioned? You merged my PR from last year fixing headless mode :-)

My apologies, because this repo is in a small little corner of github, I assumed you co-authored this with Djaenk.

**Comment by Boostem** [comment]
@wcooperscott it's all good! 

I forked and did a pull request which removes the need to be added a "contributor" just fork and work on the code and then make a pull request. @JartanFTW

**Comment by JartanFTW** [comment]
See pull request #13

**Comment by JartanFTW** [comment]
@wcooperscott Take a look here for a version with some added bugfixes and a feature to skip already completed activities. Also includes added PARTIAL support for 'run code' activities, and greatly improves the matching activities: https://github.com/JartanFTW/zyBooks-Activity-Completer/tree/master

Edit: You can disable the skipping of completed activities by setting skip_completed to False right under the headless option.

**Comment by Djaenk** [comment]
Request merged, thanks for the fixes.
