### ISSUE TITLE
Firefox Headless Client closes just after initiation 

### ISSUE THREAD

**Issue by DaoudS** [Djaenk/zyBooks-Activity-Completer#19]
Error produced from the log reads:

Traceback (most recent call last):
  File "C:\Users\daoud\Downloads\zyBooks-Activity-Completer\complete.py", line 416, in <module>
    login(driver)
  File "C:\Users\daoud\Downloads\zyBooks-Activity-Completer\complete.py", line 59, in login
    if not email:
UnboundLocalError: local variable 'email' referenced before assignment

Even after defining the email and password variables in the global variables and in a local scope to the function Simillar errors are produced.

 Enter your zybooks login below with the course code
email = ""     # "ExampleEmail@gmail.com"
course = ""    # "ExampleCourseCode"

def login(driver):
    driver.get("https://learn.zybooks.com/signin")
    while (True):
        email_input = driver.find_element_by_xpath("//input[@type='email']")
        password_input = driver.find_element_by_xpath("//input[@type='password']")
        signin_button = driver.find_element_by_class_name("signin-button")
        
        if not email:
            email = input("Please enter your zyBooks email: ")
        email_input.send_keys(myEmail)
        if (email == "quit"):
            print("--Exiting--")
            driver.quit()
            os._exit(0)

        password = getpass.getpass("Enter your zyBooks password: ")
        if (password == "quit"):
            print("--Exiting--")
            driver.quit()
            os._exit(0)

[exception.log](https://github.com/Djaenk/zyBooks-Activity-Completer/files/6689398/exception.log)
[geckodriver.log](https://github.com/Djaenk/zyBooks-Activity-Completer/files/6689401/geckodriver.log)

**Comment by ShadowXL-Dev** [comment]
I'm also having this issue. I cannot get this to open and run properly. I initialize the Firefox browser and wait about 5-10 seconds and get Headless Firefox browser closed
[exception.log](https://github.com/Djaenk/zyBooks-Activity-Completer/files/6756607/exception.log)

[exception.log](https://github.com/Djaenk/zyBooks-Activity-Completer/files/6756605/exception.log)

**Comment by Djaenk** [comment]
Fixed, sorry for the wait
