### ISSUE TITLE
Password issues

### ISSUE THREAD

**Issue by samgusick** [Djaenk/zyBooks-Activity-Completer#2]
Lets me type in my email, but when the password field shows up, I can't type anything into the command prompt so I can't get past the password stage.

**Comment by samgusick** [comment]
the password doesn't take input from the user in the code. Not sure how that's supposed to work

**Comment by Djaenk** [comment]
It does take a password input from the user, it simply doesn't show what is being typed so your password won't be compromised. If you type your password correctly and press enter the script will proceed as normal. If the password is incorrect, the script will reprompt for your email and password.

**Comment by samgusick** [comment]
Ha stupid mistake on my part. Also a CS major, and python is brand new to me so didn't know about the getpass module
