### ISSUE TITLE
Not working in January of 2020

### ISSUE THREAD

**Issue by gutsplaughter** [Djaenk/zyBooks-Activity-Completer#4]
The chapter selection appears to be broken. I cant select a chapter in my book at all. Entering any number 1-9 all results in invalid chapter. I think something may have changed with ZyBooks website and the way the chapters are selected. Any help would be appreciated!

Here is a sample

To exit the script, enter "quit" at any prompt.

Headless Firefox browswer initiated.

Please enter your zyBooks email: XXXXXX@XXXXX.edu
Enter your zyBooks password:

Login Successful

Enter your course ID or the name of your course: XXXXXXXXXXXSpring2020
zyBook Selected

Enter the chapter number you want completed: 1
--Invalid chapter--

Enter the chapter number you want completed: 2
--Invalid chapter--

Enter the chapter number you want completed: 3
--Invalid chapter--

Enter the chapter number you want completed: 4
--Invalid chapter--

Enter the chapter number you want completed:

**Comment by Djaenk** [comment]
The xpath for finding chapters and sections failed to do so, probably because the zybooks site has changed since the last time I touched the script. They've now been updated and the fix has been implemented as of release 0.2.2.
